<?php

namespace Database\Factories;

use Illuminate\Database\Eloquent\Factories\Factory;
use App\Models\User;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\Business>
 */
class BusinessFactory extends Factory
{
    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $names = [
            'Root & Rise Collective',
            'Bright Path Ventures',
            'Kindred Works',
            'The Makers Guild',
            'Harvest House Co.',
            'Bloom & Build Studio',
            'Next Chapter Collaborative',
            'Common Ground Works',
            'Everkind Enterprise',
            'Bridge & Bloom',
            'Dreamseed Co.',
            'The People’s Foundry',
            'Flourish & Flow',
            'Purpose Press Studio',
            'North Star Commons',
            'Gather & Grow Initiative',
            'The Giving Grove',
            'Civic Circle Labs',
            'Hearthlight Ventures',
            'Open Field Co.',
            'Soulcraft Collective',
            'Willow & Stone',
            'True North Co-op',
            'Rise & Root Studio',
            'The Green Thread',
            'Urban Bloomworks',
            'Hopewell Works',
            'Echo & Ember',
            'New Ground Makers',
            'The Neighborhood Engine',
        ];

        $descriptions = [
            "We help local artists turn passion into profit by offering mentorship programs, creative space access, and curated showcases that amplify their voice. Our organization believes that art is both a form of expression and a viable livelihood, and we’re committed to nurturing creativity while promoting economic independence and community empowerment. We partner with local businesses, host monthly gallery events, and offer workshops that focus on practical business skills for emerging creatives. Whether youre a painter, sculptor, musician, or multidisciplinary artist, we provide the resources and platform needed to turn your creative pursuits into a sustainable path. Our goal is to bridge the gap between artistic passion and economic opportunity, especially for creators who have traditionally been excluded from institutional support. We recognize that thriving local arts benefit the entire community, fostering cultural richness, neighborhood revitalization, and youth engagement. By reinvesting in artists, we help build a more vibrant, connected, and resilient society where creativity is valued, celebrated, and sustainable.",
            "A community-first co-op focused on ethical growth, we believe in shared success over individual profit. Our organization reinvests its proceeds into meaningful community projects like neighborhood cleanups, public school art programs, food access initiatives, and microgrants for marginalized entrepreneurs. We operate under a cooperative business model where decision-making is shared, and transparency is a non-negotiable principle. Each member has a voice, and every business choice is guided by a commitment to sustainability, fairness, and inclusion. By working collaboratively with local governments, non-profits, and grassroots organizations, we ensure our impact reaches those most in need. We don’t just talk about equity — we practice it in everything from our supply chain to our hiring practices. We measure success not by how much we extract from our community, but by how much we reinvest back into it. Our vision is a future where ethical business isn’t the exception — it’s the standard, and where economic growth always comes with a conscience.",
            "Empowering small businesses with sustainable solutions is at the core of what we do. Our team offers customized coaching, green sourcing networks, and business strategy support for entrepreneurs who want to grow without compromising their values. We believe that environmentally conscious and socially just practices can go hand-in-hand with profitability. By focusing on long-term growth over short-term gain, we help founders build companies that are built to last — rooted in community and ready to weather change. Our services range from energy audits and eco-packaging solutions to purpose-driven brand development and stakeholder mapping. We prioritize relationships over transactions and view every business we support as a potential catalyst for broader social transformation. Whether youre starting a zero-waste shop, an ethical tech platform, or a regenerative farm, we’re here to help you scale in a way that protects your mission and maximizes your impact. Sustainability isn’t just a feature — it’s the foundation we build from.",
            "Driven by values, powered by people — our organization was created to challenge the traditional business paradigm. We believe the heart of a successful venture lies in compassion, accountability, and inclusivity. We support mission-driven entrepreneurs who prioritize social good alongside financial health. Our community is composed of diverse founders, mentors, and change agents who are reimagining what business can look like when people come first. We offer capacity-building programs, community building retreats, sliding-scale consulting, and peer support groups designed to meet founders where they are. Every offering is informed by lived experience and shaped through active feedback. Our culture encourages experimentation, learning through failure, and personal growth. We work hard to dismantle harmful hierarchies and create spaces where everyone’s voice is respected. When we say people-powered, we mean it — from participatory budgeting to shared governance models, we put collaboration at the core of our work. Our ultimate goal is to create thriving ecosystems where businesses become a tool for equity, healing, and resilience.",
            "Your neighborhood hub for innovation and support, we act as a launchpad for entrepreneurs, creatives, and community leaders ready to turn bold ideas into tangible results. Our space is part coworking studio, part community center, and part think tank. We provide technical assistance, workshops, seed grants, and access to a broad network of mentors and funders. But more than that, we offer encouragement, accountability, and a belief that innovation should benefit everyone — not just the well-connected. We are especially passionate about working with individuals from underrepresented backgrounds who are often overlooked by traditional startup ecosystems. By leveling the playing field and offering no-cost or low-cost resources, we ensure that great ideas don’t stay stuck in someone’s notebook due to lack of access. Whether youre a tech founder building an app for mutual aid or an artist launching a cooperative print studio, our team is here to help you strategize, connect, and grow. At our core, we believe that every neighborhood can be a hub of innovation — when given the right tools.",
            "Crafting better futures through local partnerships, we focus on building networks that uplift entire communities through economic inclusion, skill development, and mutual support. Rather than centering on profit alone, we collaborate with nonprofits, public institutions, and grassroots organizers to create programs that bring long-term benefits to underserved populations. Whether it’s launching an incubator for immigrant-owned food businesses, supporting artists through citywide mural campaigns, or co-hosting financial literacy bootcamps, our approach is always relational, not transactional. We see local business as a vehicle for dignity, representation, and intergenerational resilience. Every project we take on is grounded in community feedback and co-designed with those we aim to support. Our belief is simple: if you want to build a better future, you have to build it with people — not for them. By focusing on strong, values-aligned partnerships, we help small business owners expand their impact, gain legitimacy, and access opportunities that were once closed to them. Together, we’re creating ecosystems where business becomes a bridge — not a barrier — to justice and joy.",
            "Women-led, community-backed, and future-focused, we exist to center voices historically excluded from the business world and create structures that prioritize care, collaboration, and power-sharing. Our programs are designed for women, trans, and non-binary entrepreneurs who want to build on their own terms, free from the toxic hustle culture that dominates startup spaces. We offer flexible funding, trauma-informed coaching, and leadership training that draws on lived experience rather than rigid corporate templates. We believe you don’t have to choose between ambition and wellbeing — you can grow something meaningful while staying grounded and whole. From collective childcare stipends to anti-oppression business planning, our supports are crafted to meet the realities of our community. We work with founders building everything from social justice media companies to regenerative farms, ensuring each receives the resources and confidence they need to flourish. At our core, we exist to build the business world we wish we had — one where no one has to burn out just to be seen.",
            "We invest in people, not just profits. For us, success is measured not by revenue but by how many lives are positively impacted through meaningful, inclusive entrepreneurship. We work with early-stage founders to build ventures rooted in purpose, justice, and long-term sustainability. Our process begins with relationship-building: learning each entrepreneur’s story, struggles, and aspirations. From there, we develop tailored support — from low-interest community loans to mental health counseling to group strategy sessions with peer founders. Many of our members come from marginalized backgrounds and carry the weight of exclusion from traditional financial and professional networks. We’re here to change that. Every dollar we grant or lend is seen as a vote of confidence in someone’s potential — not just a transaction. We believe business should reflect the best of who we are: generous, creative, and deeply interconnected. Our community proves every day that when people are resourced and believed in, they don’t just grow — they transform everything around them.",
            "Socially conscious and proudly independent, we are a hub for purpose-driven entrepreneurs who refuse to compromise ethics for scale. Our work is rooted in radical transparency, equity, and community stewardship. We guide founders through the often murky waters of ethical growth, providing tools to navigate supply chains, investor relationships, and labor practices with integrity. Our philosophy is simple: doing good is not a branding strategy — it’s a baseline requirement. That’s why we prioritize accountability mechanisms, shared ownership structures, and values-aligned marketing. We also help founders become storytellers — articulating their mission clearly and compellingly so they can connect authentically with customers and collaborators. Whether launching a plastic-free packaging line or a worker-owned wellness studio, our members are building businesses that serve as antidotes to extractive models. We celebrate slow, sustainable scaling and recognize that impact often grows person by person, not just platform by platform. In a world where exploitation is often disguised as innovation, we stand as proof that success and conscience can — and must — coexist.",
            "Turning dreams into plans, and plans into impact — that’s what we do best. We work with entrepreneurs who have bold visions for their communities but lack the structural support to make them real. Through our program, founders receive step-by-step guidance that transforms abstract ideas into actionable strategies. We start by clarifying purpose, mapping out community needs, and identifying sustainable business models that align with the founder’s ethics. From there, we provide hands-on coaching, accountability check-ins, and connection to an extensive mentor and funder network. Many of our participants are navigating business ownership for the first time, and we ensure they never have to do it alone. We celebrate experimentation and create space for trial and error — because learning is just as important as launching. By the end of our cohort, founders leave not just with a business plan, but with confidence, clarity, and a supportive community behind them. We don’t just help people build businesses — we help them become builders of change, resilience, and possibility.",
            "We’re more than a business incubator — we’re a movement for economic justice. Our programs are designed to shift power into the hands of those historically excluded from entrepreneurship due to race, class, gender, or ability. We don’t just teach people how to run a business; we help them unlearn harmful norms and build new models rooted in care, accountability, and shared prosperity. Our curriculum includes cooperative business design, equity-centered marketing, conflict resolution, and boundary-setting in leadership. We also host healing circles, political education sessions, and peer accountability groups. This isn’t business as usual — it’s business in service of liberation. We work with everyone from mutual aid organizers launching community cafes to youth leaders designing tech tools for housing justice. By offering culturally relevant and structurally aware support, we ensure our members are equipped not only to survive in the market but to shape it. We believe business doesn’t have to uphold the systems that harm us — it can be a vehicle to dismantle them, while building something better in their place.",
            "From idea to execution, we walk alongside entrepreneurs as they navigate the messy, nonlinear journey of building something new. We know that launching a business isn’t just about spreadsheets and pitch decks — it’s also about doubt, burnout, risk, and resilience. That’s why our programs are structured with both heart and strategy. We offer access to business advisors, legal clinics, mental health counselors, and creative coaches to support the whole entrepreneur. Our founders aren’t just building brands; they’re building legacies, reclaiming narratives, and healing communities. We hold space for this depth, while offering the practical tools needed to bring visions to life. Our approach is trauma-informed, flexible, and deeply relational. You won’t find one-size-fits-all models here — just real people doing brave work, supported by a team who believes in their potential. We don’t just want to see businesses succeed; we want to see entrepreneurs thrive — mentally, financially, and spiritually.",
            "Rooted in trust and driven by purpose, we provide a safe, collaborative space where innovators can explore, fail, learn, and grow. We understand that building a business is deeply personal — and often intimidating — especially for those without generational wealth or formal networks. That’s why we focus on trust-building before business-building. Our community is built around mutual respect, peer accountability, and shared learning. Whether you’re refining your product, pitching your first investor, or navigating co-founder conflict, we provide compassionate guidance every step of the way. We offer low-barrier funding, legal templates in plain English, anti-racism training, and mental health stipends to make sure you’re resourced inside and out. More than anything, we believe you shouldn’t have to become someone else to succeed. You should be able to build as yourself, for your community, in alignment with your values. We hold space for that process and celebrate the strength it takes to build something honest in a world that often rewards the opposite.",
            "Through accessible workshops, culturally responsive coaching, and direct capital support, we uplift business owners whose identities and ideas are often excluded from the mainstream entrepreneurial narrative. Our organization was born out of a desire to bridge the massive gap between potential and access — the gap that so many BIPOC, LGBTQ+, disabled, and low-income founders fall through. We offer business planning classes in multiple languages, provide support navigating government grants, and host storytelling bootcamps to help founders own their narratives. Our staff and mentors share lived experience with the communities we serve, which makes trust and relatability foundational to our approach. We know that representation is not a buzzword — it’s the baseline. In every room we create, people feel seen, supported, and powerful. Our dream is a future where the entrepreneurial playing field isn’t just level — it’s just, welcoming, and reflective of the world we want to live in. Until then, we’ll keep building the bridges others refuse to.",
            "Built on radical transparency and mutual respect, our organization centers community in every decision we make. We believe that the people most affected by business outcomes should be the ones shaping its direction. That’s why our governance structure includes rotating community advisory boards, open budgeting processes, and participatory policy design. Every new program we launch starts with listening — not assumptions. We host town halls, facilitate multilingual feedback sessions, and prioritize ongoing dialogue with our stakeholders. Our transparency goes beyond finances; it includes sharing challenges, mistakes, and lessons learned. We believe that by being honest about our growth, we make room for others to grow with us. We apply the same philosophy to the businesses we support, encouraging founders to lead with humility, curiosity, and community accountability. In a world where opacity is often the default, we choose to build in the light — and invite others to do the same.",
            "We believe the future of business is local, inclusive, and people-powered. Our work centers on helping community-rooted founders bring their visions to life in a way that honors their values and culture. We support cooperative models, neighborhood-based mutual aid ventures, and social enterprises that prioritize the well-being of their workers and customers. Our programs are tailored to the unique challenges and strengths of local economies. Whether we’re helping a community garden launch a produce delivery service or supporting a coalition of childcare providers in forming a cooperative, we start with what’s already working — and help it grow. We also advocate for policy change at the municipal level to make local entrepreneurship more accessible. We believe that when small businesses succeed, neighborhoods thrive. And when those businesses are owned and operated by the people who live there, the ripple effects are exponential. It’s not just about economics — it’s about dignity, sovereignty, and belonging.",
            "As a social enterprise accelerator, we guide mission-driven founders in turning local challenges into scalable impact. Our programming includes intensive bootcamps, mentorship from experienced impact investors, and access to a community of changemakers who understand that solving social problems is both an art and a science. We help participants refine their theories of change, develop sustainable revenue models, and measure their impact in ways that go beyond vanity metrics. From climate resilience to youth empowerment, we work across sectors to foster innovation that centers equity and accountability. Our support doesn’t stop after launch — we offer long-term alumni engagement, access to growth-stage funding, and opportunities for peer leadership. We understand that impact work is emotionally taxing, so we prioritize founder well-being through trauma-informed facilitation and burnout prevention resources. Our goal is to ensure that every founder in our network not only builds a strong organization but also builds a life where their values and capacity are honored equally.",
            "We exist to carve out space in industries that have long excluded underrepresented voices. Our programming is designed to help historically marginalized founders gain the knowledge, tools, and confidence to navigate sectors that weren’t built for them. We offer technical training in industries like tech, clean energy, sustainable agriculture, and media production — but we also work to transform those industries by showing that leadership can look, sound, and operate differently. Our community events bring together founders, investors, artists, and organizers to reimagine what power-sharing can look like. We fund collaborative experiments, support creative risk-taking, and actively dismantle gatekeeping wherever we find it. Most importantly, we believe that inclusion is not about getting a seat at someone else’s table — it’s about building new tables altogether. We’re here to make sure that founders who’ve been underestimated at every turn now have the space, structure, and community to thrive.",
            "Our collective walks beside entrepreneurs as they transform sparks of inspiration into lasting institutions. We believe business can be a form of love — a way to care for your community, meet collective needs, and build interdependence. That’s why we offer wraparound services that support both the practical and emotional sides of entrepreneurship. We help founders map their business ecosystems, identify aligned collaborators, and design for impact without burnout. Our team includes coaches, healers, lawyers, accountants, and artists — because building a mission-driven business requires a mosaic of expertise. We treat every venture as a living system and help founders develop practices that foster resilience, creativity, and adaptability. Whether launching a worker-owned cafe or a community wellness center, our members leave our programs with not just a business — but a worldview and a support network to carry it forward.",
            "We provide a soft landing for bold ideas — especially ones that challenge the status quo. We understand that visionary thinkers are often told to shrink their ideas to fit existing molds. Here, we do the opposite: we help you expand. Our incubator is built for people who see problems as opportunities to redesign systems — whether in education, food access, healthcare, or local governance. We provide design thinking labs, storytelling residencies, and experimental funding rounds for founders pushing boundaries. We pair each entrepreneur with a care team to support their emotional, strategic, and operational needs. We also train funders and partners in how to work with unconventional thinkers without diluting their vision. Most importantly, we hold space for doubt, recalibration, and failure — because innovation isn’t linear, and neither is growth. If you’ve ever felt like your idea was “too much,” “too radical,” or “too different,” this is the place for you. We’re not here to make you palatable — we’re here to help you stay powerful.",
            "With a deep focus on circular economies and regenerative business practices, we support founders who are rethinking consumption and designing solutions that restore rather than deplete. Our organization works with entrepreneurs in fashion, food systems, packaging, and home goods to help them embed sustainability into every layer of their work. We offer lifecycle assessments, material innovation labs, and values-driven sourcing strategies. We also connect our members with climate-conscious investors and product testers who understand the rigor and creativity behind building a low-waste business. From refillable soap companies to upcycled denim brands, our members are setting a new standard for what responsibility can look like in business. We believe sustainability isn’t a trend — it’s a mindset shift. Our goal is to make regeneration the default and show that businesses can succeed not in spite of their ethics, but because of them.",
            "We equip grassroots changemakers with the tools, support, and visibility they need to scale without losing sight of their values. Our program is designed for community-based leaders working on hyper-local solutions — whether it’s mutual aid networks, neighborhood beautification projects, or food justice initiatives. We offer strategy sessions, small business grants, and storytelling platforms that help these efforts grow while staying rooted in local accountability. We also provide tech and infrastructure training so leaders can streamline operations, gather data ethically, and apply for larger funding without burning out. Every resource we offer is adaptable to the unique pace and priorities of grassroots work. Our belief is simple: big change often starts small — with trusted leaders doing invisible labor. We’re here to shine a light on that work and help it flourish on its own terms.",
            "We support artisans, makers, and creatives who want to build lasting careers without compromising their artistic vision. Too often, creative people are told to “get a real job” or sell out to survive. We reject that narrative entirely. Our programs combine financial literacy, retail strategy, and personal coaching to help creatives thrive on their own terms. From pop-up markets to e-commerce mentorship, we help participants expand their audiences and increase revenue while staying grounded in their values. We also offer communal studio space, collaborative grant writing sessions, and curated wholesale partnerships that celebrate originality over mass production. Creativity is a form of labor, and it deserves sustainability. Whether you're a ceramicist launching a subscription box or a poet starting a publishing co-op, we provide the structure and encouragement to build a business that reflects who you are — without losing what makes your work special.",
            "Our mission is to democratize access to opportunity through an ecosystem of equity-based funding, multilingual education, and trauma-informed coaching. We recognize that traditional business spaces are often hostile to those without generational wealth, English fluency, or formal credentials. That’s why we’ve built a network where accessibility isn’t an afterthought — it’s the starting point. Our programs include language-accessible business planning, childcare stipends, and flexible coaching hours that honor real-life responsibilities. We offer low-barrier microloans, legal navigation support, and culturally relevant mentorship. We also train our funders to move at the speed of trust and adopt practices that prioritize listening over metrics. Our community includes immigrant founders, disabled creatives, single parents, and formerly incarcerated leaders — all building businesses that matter. We believe everyone has a right to build, dream, and grow. We’re here to ensure the path is clear and the support is real.",
            "We believe long-term impact starts with thoughtful, values-aligned planning. While many accelerators focus solely on product-market fit and profitability, we go deeper — helping founders explore how their internal compass shapes external outcomes. We offer one-on-one coaching on mission clarity, ethical decision-making, and social impact strategy. Our leadership labs explore topics like intergenerational wealth, non-extractive scaling, and trauma-aware management. We also support operational planning through tools that encourage reflection and community accountability, not just growth metrics. Founders leave our program not only with a roadmap for revenue but with practices that keep their work sustainable and human-centered. We’ve found that when entrepreneurs are given space to align their purpose with their strategy, they create businesses that last longer, feel better, and do more good. That’s the kind of legacy we believe in — one that’s grounded, intentional, and deeply rooted in care.",
            "We’re cultivating a new generation of leaders who define success on their own terms. Our work is rooted in the belief that community ownership, ecological stewardship, and labor dignity should be cornerstones of any modern business. We support cooperatives, social enterprises, and solo entrepreneurs building ventures that redistribute power and prioritize wellbeing. Our programs include curriculum on collective governance, environmental accountability, and intergenerational leadership. We also provide intercohort dialogue spaces where founders can learn from one another’s models and mistakes. Many of our members come from communities who have long been exploited by capitalism — now, they’re reshaping it from the inside out. From rural land trusts to youth-led media co-ops, we support work that centers liberation, not just innovation. Our goal is not just to change who gets to lead, but how leadership looks, feels, and flows.",
            "Whether you’re baking bread, writing code, or growing food, we’re here to support you with actionable plans, peer support, and flexible funding. We understand that many dreamers are already doing the work — they just need structure and community to scale it. Our cohort program starts by validating your vision and helping you refine your 'why.' From there, we help map operations, budget realistically, and build sustainable outreach. We provide weekly accountability calls, expert Q&A sessions, and tools for tracking both financial and emotional ROI. Participants finish with clarity, confidence, and a solid pitch deck — whether they’re seeking capital or simply trying to organize next steps. But most importantly, they leave with a peer network that believes in their work. We don’t care what industry you’re in — we care that you’re doing it with heart.",
            "We guide purpose-driven entrepreneurs toward balance, impact, and longevity. In our experience, founders often sacrifice their wellbeing in pursuit of a mission — and eventually burn out. Our approach is different. We incorporate wellness and sustainability into the core of every business plan. Our curriculum includes topics like boundaries in leadership, healing from hustle culture, and designing for rest. We also offer access to somatic coaches, sliding-scale therapy partners, and community wellness grants. Many of our alumni say our program was the first time they felt “permission to slow down” and still be taken seriously. We remind founders that rest is not a reward — it’s a right. Businesses built with wellbeing in mind don’t just last longer — they feel better to run and lead to healthier communities. You shouldn’t have to choose between impact and peace. We’re here to show you how to have both.",
            "We offer trauma-aware business support for people whose lived experiences make traditional accelerators inaccessible or unsafe. Our team includes facilitators trained in mental health first aid, harm reduction, and peer support. We don’t ignore pain — we integrate it with care. From our intake form to our grant applications, we design every touchpoint to minimize re-traumatization and maximize autonomy. We never require public speaking or performative vulnerability to prove worthiness. We allow people to show up however they can, and we support them with flexibility and compassion. We understand that success looks different for everyone — and that healing is a legitimate business goal. Many of our members are survivors, caregivers, or justice-impacted founders building new paths in the face of deep systemic harm. We honor that work fully. You are not broken. You are building. We’re here to walk with you.".
            "Our ecosystem is built to reverse generational inequity. We combine capital access, mentorship, education, and peer solidarity to help historically excluded founders build lasting businesses. Our grants are relationship-based — not pitch-based — and our curriculum includes intergenerational wealth-building, power analysis, and legacy design. We also facilitate kinship networks across founders so they’re never alone, even when the work gets hard. Every dollar we give, every connection we make, is a step toward a future where Black, Indigenous, immigrant, and low-income entrepreneurs have the resources and recognition they deserve. We’re not interested in band-aids. We’re building infrastructure — emotional, relational, and financial — that supports long-term transformation. This is more than business. This is justice in motion."
        ];

        return [
            'user_id' => User::factory(), // Create new user for each listing
            'name' => $this->faker->unique()->randomElement($names),
            'address1' => $this->faker->streetAddress,
            'city' => $this->faker->city,
            'state' => $this->faker->state,
            'zip_code' => $this->faker->postcode,
            'phone_number' => $this->faker->phoneNumber,
            'featured' => $this->faker->boolean(25),
            'business_description' => $this->faker->randomElement($descriptions),
        ];
    }
}
